# 本地開發用（處理 Zscaler SSL）
FROM node:20-slim

WORKDIR /app

# 先裝最基本工具
RUN apt-get update && apt-get install -y \
	ca-certificates \
	curl

# 處理 Zscaler SSL 憑證
ARG ZSCALER_CERT_PATH
COPY ${ZSCALER_CERT_PATH} /usr/local/share/ca-certificates/Zscaler_Root_CA.crt
RUN update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/Zscaler_Root_CA.crt

# 安裝 yt-dlp、ffmpeg 與 SSL 工具
RUN apt-get update && apt-get install -y \
	python3 \
	ffmpeg \
	# curl \
	# ca-certificates \
	&& curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp \
	&& chmod a+rx /usr/local/bin/yt-dlp \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# 確保 yt-dlp 在 PATH
ENV PATH="/usr/local/bin:${PATH}"

# 複製 package.json
COPY package.json .

# 安裝 Node.js 依賴
RUN npm install

# 複製程式碼
COPY . ./

EXPOSE $PORT

CMD ["npm", "start"]
